export interface Subscription {
  id: string
  user_id: string
  name: string
  feed_url: string
  filter: string
  media_type?: string
  media_category?: string
  save_path?: string
  search_mode?: string
  imdb_id?: string
  source?: string
  poster_url?: string
  backdrop_url?: string
  overview?: string
  resolution?: string
  quality?: string
  effects?: string
  release_groups?: string
  exclude_words?: string
  wash_enabled?: boolean
  wash_priority?: string
  total_episodes?: number
  downloaded_episodes?: number
  local_media_count?: number
  missing_episodes?: number[]
  in_library?: boolean
  priority?: number
  enabled: boolean
  last_run_at?: string
  archived_at?: string
  archive_reason?: string
  created_at: string
  updated_at: string
}
